# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  displayName: Install terraform
  inputs:
    terraformVersion: 'v0.14.6'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: 'azurermVersion:2.41.0'
    backendServiceArm: 'checkfor tee'
    backendAzureRmResourceGroupName: 'terraform-dp'
    backendAzureRmStorageAccountName: 'dataplugin'
    backendAzureRmContainerName: 'dpstate'
    backendAzureRmKey: 'snapshotest.tfstate'
  
